# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.srcs/sources_1/bd/design_1/ip/design_1_rmii_0_0/design_1_rmii_0_0.xci
# IP: The module: 'design_1_rmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_rmii_0_0/src/data_fifo/data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] -quiet

# XDC: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_rmii_0_0/src/data_fifo/data_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.srcs/sources_1/bd/design_1/ip/design_1_rmii_0_0/design_1_rmii_0_0.xci
# IP: The module: 'design_1_rmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_rmii_0_0/src/data_fifo/data_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] -quiet

# XDC: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_rmii_0_0/src/data_fifo/data_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
