# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
# IP: The module: 'design_1_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
# IP: The module: 'design_1_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ehs/Desktop/test/Ethernet/modify_src/proj_ethernet/proj_ethernet.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
